name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Checking Tests
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
            npm install
            npm run build
            npm run seed
            npm run start
            npm run test

      - name: Deploy To Render
        if: github.ref == 'refs/heads/main'
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$DEPLOY_URL"
